export const data = [
    {
        id: 1,
        projectNumber: 'SCA002001',
        firstName: 'Liam',
        lastName: 'Smith',
        date: '01/02/2025',
        comp: 'Alpha Inc.',
        numImages: '50',
        status: 'Pending Processing',
        goodImages: '90',
        delete: '',
    },
    {
        id: 2,
        projectNumber: 'SCA002002',
        firstName: 'Emma',
        lastName: 'Johnson',
        date: '03/02/2025',
        comp: 'Beta Corp.',
        numImages: '35',
        status: 'Processing Failed',
        goodImages: '78',
        delete: '',
    },
    {
        id: 3,
        projectNumber: 'SCA002003',
        firstName: 'Olivia',
        lastName: 'Brown',
        date: '05/02/2025',
        comp: 'Gamma Ltd.',
        numImages: '60',
        status: 'Processing Successful',
        goodImages: '95',
        delete: '',
    },
    {
        id: 4,
        projectNumber: 'SCA002004',
        firstName: 'Noah',
        lastName: 'Williams',
        date: '07/02/2025',
        comp: 'Delta Group',
        numImages: '42',
        status: 'DXF Exported',
        goodImages: '88',
        delete: '',
    },
    {
        id: 5,
        projectNumber: 'SCA002005',
        firstName: 'Sophia',
        lastName: 'Jones',
        date: '09/02/2025',
        comp: 'Epsilon Partners',
        numImages: '55',
        status: 'Pending Processing',
        goodImages: '82',
        delete: '',
    },
    {
        id: 6,
        projectNumber: 'SCA002006',
        firstName: 'James',
        lastName: 'Taylor',
        date: '11/02/2025',
        comp: 'Zeta Solutions',
        numImages: '37',
        status: 'Processing Failed',
        goodImages: '76',
        delete: '',
    },
    {
        id: 7,
        projectNumber: 'SCA002007',
        firstName: 'Charlotte',
        lastName: 'Anderson',
        date: '13/02/2025',
        comp: 'Eta Innovations',
        numImages: '65',
        status: 'Processing Successful',
        goodImages: '91',
        delete: '',
    },
    {
        id: 8,
        projectNumber: 'SCA002008',
        firstName: 'Benjamin',
        lastName: 'Moore',
        date: '15/02/2025',
        comp: 'Theta Analytics',
        numImages: '40',
        status: 'DXF Exported',
        goodImages: '85',
        delete: '',
    },
    {
        id: 9,
        projectNumber: 'SCA002009',
        firstName: 'Ava',
        lastName: 'Martin',
        date: '17/02/2025',
        comp: 'Iota Systems',
        numImages: '48',
        status: 'Processing Failed',
        goodImages: '83',
        delete: '',
    },
    {
        id: 10,
        projectNumber: 'SCA002010',
        firstName: 'Ethan',
        lastName: 'Garcia',
        date: '19/02/2025',
        comp: 'Kappa Designs',
        numImages: '53',
        status: 'Processing Successful',
        goodImages: '92',
        delete: '',
    },
    {
        id: 11,
        projectNumber: 'SCA002011',
        firstName: 'Amelia',
        lastName: 'Martinez',
        date: '21/02/2025',
        comp: 'Lambda Tech',
        numImages: '58',
        status: 'Pending Processing',
        goodImages: '87',
        delete: '',
    },
    {
        id: 12,
        projectNumber: 'SCA002012',
        firstName: 'Logan',
        lastName: 'Hernandez',
        date: '23/02/2025',
        comp: 'Mu Dynamics',
        numImages: '45',
        status: 'DXF Exported',
        goodImages: '89',
        delete: '',
    },
    {
        id: 13,
        projectNumber: 'SCA002013',
        firstName: 'Isabella',
        lastName: 'Lopez',
        date: '25/02/2025',
        comp: 'Nu Enterprises',
        numImages: '52',
        status: 'Processing Failed',
        goodImages: '80',
        delete: '',
    },
    {
        id: 14,
        projectNumber: 'SCA002014',
        firstName: 'Mason',
        lastName: 'Hill',
        date: '27/02/2025',
        comp: 'Omicron Solutions',
        numImages: '47',
        status: 'Processing Successful',
        goodImages: '94',
        delete: '',
    },
    {
        id: 15,
        projectNumber: 'SCA002015',
        firstName: 'Mia',
        lastName: 'Scott',
        date: '01/03/2025',
        comp: 'Pi Innovations',
        numImages: '49',
        status: 'Pending Processing',
        goodImages: '84',
        delete: '',
    },
    
];
